[main]
description = "brief description of the cli tool"

[links]
issue_tracker = "https://www.github.com/uraneko/jagaimo/issues"
src_code = "https://www.github.com/uraneko/jagaimo"
website = "???"

[links.extra]
github = "https://www.github.com/uraneko"

[spaces]
collections = "operations for managing collections"

[operations]
"*.add" = "create a new item and add it to existing group"

# this superseed the above general description for the add ope when the space is collections 
collections.add = "add a new collection to the collections database"

[flags]
root.size = "specify the size of the item"

# this specific rule supersedes any other limit flag rule for command history query --limit
history.query.limit = "sets the limit of the history query results count"
