[main]
description = "brief description of the cli tool"

[links]
issue_tracker = "https://www.github.com/uraneko/jagaimo/issues"
src_code = "https://www.github.com/uraneko/jagaimo"
website = "???"

[links.extra]
github = "https://www.github.com/uraneko"

[[space]]
collections = "operations for managing collections"

[[operation]]
"*.add" = "create a new item and add it to existing group"

[[operation]]
name = "add"
scope = "collections" 
# this superseed the above general description for the add ope when the space is collections 
content = "add a new collection to the collections database"

[[flag]]
root.size = "specify the size of the item"

[[flag]]
# this specific rule supersedes any other limit flag rule for command history query --limit
history.query.limit = "sets the limit of the history query results count"
